### ISSUE TITLE
GenFEVD with a penalty

### ISSUE THREAD

**Issue by Manfretto** [tomaskrehlik/fftSpillover#11]
Dear,

Many thanks for creating these functions, really stunning!

However, I would like to use a Penalized Vector Autoregression instead of the regular VAR estimates, as is required in the function. Can you help me how I can implement a penalized VAR estimate? I would like to for example make an implementation with the Big.Var package from R, since that one has a LASSO penalty option.

Hope to hear from you!

Best,

Bart

**Comment by tomaskrehlik** [comment]
There is an example of Big.Var estimation in the [README](https://github.com/tomaskrehlik/frequencyConnectedness) page.
