### ISSUE TITLE
fevd

### ISSUE THREAD

**Issue by Allennnnnnnn** [tomaskrehlik/fftSpillover#12]
hi!
While reading your r-code, I see that you say you use the standard forecast error variance decomposition (genFEVD). As I remember, the paper suggest that we need to use the generalized fevd, because fevd can depend on the order of variables. Since I'm not so good at r-coding, did I misunderstand and the genFEVD is exactly the generalized fevd? 

best regards!
Allen

**Comment by tomaskrehlik** [comment]
That would be right.
