### ISSUE TITLE
the "bounds" and the requests about "n.ahead" and "window" on the spilloverRollingxx functions

### ISSUE THREAD

**Issue by Allennnnnnnn** [tomaskrehlik/fftSpillover#13]
Hi,
Is there any lower bound for the parameter "n.ahead" and "window" using the spilloverRollingXX functions?
While setting "bounds <- c(pi+0.00001, pi/5, pi/20, pi/300)", I have to let the n.ahead and window be larger than some number, otherwise there're some errors or you get NA results.

**Comment by tomaskrehlik** [comment]
To perform the Fourier transform one needs at least certain amount of data. As in one of the examples:

```
# Get the frequency connectedness on partition (pi,pi/4), (pi/4,0), roughly
# corresponding to movements of 1 to 4 days and 4 to longer.
bounds <- c(pi+0.00001, pi/4, 0)
```

one would need `n.ahead` certainly higher than 4 to approximate any movement of 4 days and longer... In general, the decomposition should be done on _infinite_ fevd so you should ideally have `n.ahead` as high as possible.
