### ISSUE TITLE
Is there any restriction for the param. “n.ahead” while using the function "spilloverRollingBK12"?

### ISSUE THREAD

**Issue by Allennnnnnnn** [tomaskrehlik/fftSpillover#15]
Is there any restriction for the param. “n.ahead” while using the function "spilloverRollingBK12"?

With regard to my data set, for the bounds: "bounds <- c(pi+0.00001, pi/5, pi/20, pi/300)"，the function cannot be performed.

the code:
bounds <- c(pi+0.00001, pi/5, pi/20, pi/300)
sp_20_f <- spilloverRollingBK12(ES, n.ahead = 20, no.corr = F, func_est = "VAR", params_est = params_var,  
                                                    window = 60, partition = bounds)

**Comment by tomaskrehlik** [comment]
Please stop resubmitting the same issue https://github.com/tomaskrehlik/frequencyConnectedness/issues/13
