### ISSUE TITLE
Unable to convert output into data frame to export to excel

### ISSUE THREAD

**Issue by akuokoangelo** [tomaskrehlik/fftSpillover#23]
Whenever i try to convert the output from the package i get this error message:

Error in as.data.frame.default(dieb) : 
  cannot coerce class ‘"spillover_table"’ to a data.frame

Please, help me in dealing with this issue.
Thanks

**Comment by tomaskrehlik** [comment]
Hi Angelo,

the spillover table estimate (let's call it `sp_table`) has a field called `tables`, so you can do `sp_table$tables[[1]]` to get your data frame.
