### ISSUE TITLE
To and From Calculation

### ISSUE THREAD

**Issue by tangdale** [tomaskrehlik/fftSpillover#5]
Dear Professor,
         I have a quick question about the To and From spill over effect calculation. As you can see, the To-V1 effect should be 2.65+0.31=2.94, but you give 0.99 instead. I am wondering whether do I misunderstand here? Thanks!

## |TO | 0.99|  2.44| 57.10| 60.53|

Best,
Chao

**Comment by EhsanBagherii** [comment]
hello.
I have this problem too.
Can you help me please?

**Comment by tomaskrehlik** [comment]
The effects are divided by k, where k is the number of variables to give a neat sum up in the table. It is only a matter of standardization.
