### ISSUE TITLE
Pairwise spillovers - How are they calculated and are they net pairwise spillovers ?

### ISSUE THREAD

**Issue by nsobti5** [tomaskrehlik/fftSpillover#6]
Dear Sir 

I see some issue with Diebold Yilmaz pairwise spillovers results. I am using the same example as you have shown in your example on 
https://github.com/tomaskrehlik/frequencyConnectedness

# Compute the VAR(2) estimate with constant and save results
est <- VAR(exampleSim, p = 2, type = "const")

sp <- spilloverDY12(est, n.ahead = 100, no.corr = T)
sp

## 
## 
## |TO | 0.44|  2.79| 58.02| 61.25|

pairwise(sp)

##  2.350667 28.668472 29.196572

Sir I am unable to understand how are these pairwise spillovers results being calculated in your package as what i see on spillover table sp is that 
V1-V2 = 8.15
V2-V1=1.10

How did this pairwise V1-V2 =2.350667 being calculated as if i subtract 8.15-1.10 = 7.05 

I need **net pairwise directional spillovers** . Can you please guide , what is wrong with my understanding of code ?

**Comment by tomaskrehlik** [comment]
The spillover is scaled by number of variables in the system, 2.35*3 = 7.05. Depends on what definition you want to use for computation of your spillovers.
