### ISSUE TITLE
Identical Scaling of Plots

### ISSUE THREAD

**Issue by alfonsebert** [tomaskrehlik/fftSpillover#7]
Is there any possibility to scale the plots identically so they are easier to compare to each other?
And is there also a possibility to plot pairwise spillovers for different window sizes in one plot? 

Thank you very much!

**Comment by tomaskrehlik** [comment]
The code to produce plots is in the following file https://github.com/tomaskrehlik/frequencyConnectedness/blob/master/R/list_of_spills_methods.R#L207 and should be easy to adapt to your cases.

Feel free to post the upgrades as a pull request, will be very much appreciated.
