### ISSUE TITLE
pairwise spillovers only for lower diagonal of FEVD

### ISSUE THREAD

**Issue by LukasEcon** [tomaskrehlik/fftSpillover#8]
Dear Thomas,

Many thanks for publishing your code!
Could you explain why it is only possible to calculate pairwise spillovers for the lower diagonal of the FEVD for rolling window estimations? Those pairwise spillovers should not be symmetric, if I am not wrong. (Whether they have a structural meaning is of course a different question...)

Many thanks in advance.
Best,
Lukas

**Comment by tomaskrehlik** [comment]
Hello Lukas,

look for example [here](https://www.nber.org/papers/w17490.pdf), the pairwise spillovers as they are named in the package correspond to something called net-pairwise in the paper. The standard pairwise spillovers are the elements of the spillover table itself.
