### ISSUE TITLE
Rolling spillover

### ISSUE THREAD

**Issue by Asimshaikh1986** [tomaskrehlik/fftSpillover#9]
When I run the code for Rolling spillover I get an error " | 0 % ~calculating  Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :  contrasts can be applied only to factors with 2 or more levels
In addition: Warning message:
In storage.mode(v) <- "double" : NAs introduced by coercion"

**Comment by Allennnnnnnn** [comment]
I got the same error too... Did u solve the problem?

**Comment by huichaoDU** [comment]
I got the same error to too too..." | 0 % ~calculating Error in (function(y,p=1,type=c("const","trend","both","none"),:The matrix 'y' should contain at least two variables.
what's wrong with this?

**Comment by huichaoDU** [comment]
> I got the same error too... Did u solve the problem?

did u solve the problem?

**Comment by Allennnnnnnn** [comment]
yeah，because my initial dataset had some na values, and I solved the problem by just omit the NAs



在 2020-10-16 10:44:41，"huichaoDU" <notifications@github.com> 写道：

I got the same error too... Did u solve the problem?

did u solve the problem?

**Comment by huichaoDU** [comment]
thk u！l also have solved my question，it is always a little basic error🤓

发自我的iPhone

**Comment by tomaskrehlik** [comment]
I amended the package so that the rolling estimation should fail fast on data that has NAs. See version 0.2.3
